spring:
  datasource:
    url: jdbc:mysql://localhost:3306/android?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

server:
  port: 8087

# 七牛云
oss:
  accessKey: jCn6WFVZEpsKA0-8VsDTO8_FPwEdzIaDym3hO03N
  secretKey: MzgNsh60V7zqaSt5VGf-ZVejwO-c3HsiJ9yVWl2t
  bucket: ityyp-blog
  qiniu:
    domain: http://rvgc72vz1.hb-bkt.clouddn.com # 访问域名(默认使用七牛云测试域名)
    accessKey: jCn6WFVZEpsKA0-8VsDTO8_FPwEdzIaDym3hO03N # 公钥
    secretKey: MzgNsh60V7zqaSt5VGf-ZVejwO-c3HsiJ9yVWl2t # 私钥
    bucketName: ityyp-blog  #存储空间名称